# Name of your blog (this will show up at the top of your page and in the RSS feed)
name: Unix Way

# Short description (goes below the title; it will also be used in the RSS feed)
description: "Блог Павла Вязового aka Paul Elms"

# Your name, as you want it to appear underneath each post and in the footer
author: Павел Вязовой

# Your email if you want it to be linked on the contact page
author_email: paul@elms.pro

# The directory for category index pages. Change it to something else if
# for example you want links like /categories/category1 instead of /category1
category_dir: blog/categories

url: http://paul.elms.pro
permalink: /blog/:year/:month/:day/:title/

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude:
  - README.md

plugins:
  - jekyll-sitemap